{% set name = "tbats" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tbats-{{ version }}.tar.gz
  sha256: dccd0d4cd9e2fde30bf19a944ee957d2f865975846284f48ce673992c4f5d89e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
  run:
    - numpy
    - pmdarima
    - python >={{ python_min }}
    - scikit-learn
    - scipy

test:
  imports:
    - tbats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intive-DataScience/tbats
  summary: BATS and TBATS for time series forecasting
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hrzn
    - tomasvanpottelbergh
    - gnwhr
